<?php


$labels['header_title']  = 'Verifica Firma';				      
$labels['deliveredto'] = 'Consegnato a';
$labels['mailaddress'] = 'e-mail';
$labels['deliveredfrom'] = 'Consegnato da';
$labels['validfrom'] = 'Valido da';
$labels['validto'] = 'Valido fino a';
$labels['serial'] = 'Seriale';

$messages['invalidsignature'] =  'La firma per questo messaggio non risulta verificata.';
$messages['expiredcert'] = 'La firma per questo messaggio risulta verificata ma il relativo certificato è scaduto.';
$messages['signed'] = 'Questo messaggio &egrave; firmato';
$messages['notmodified'] = 'Il messaggio non &egrave; stato modificato';
$messages['verifiedcert'] = 'Il certificato &egrave; verificato';
$messages['matchingaddress'] = 'L\'indirizzo mittente corrisponde al certificato allegato';
$messages['certinfo'] = 'Info sul certificato'; 

?>


